// <auto-generated />
using System;
using Admin_Panel_Olusturma.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin_Panel_Olusturma.Migrations
{
    [DbContext(typeof(FerhatKahyaDbContext))]
    [Migration("20220723093753_updatev3")]
    partial class updatev3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.BlogKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("BlogKategorileri");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Bloglar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Bloglar");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.GaleriKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("GaleriKategorileri");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.ReferansKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("ReferansAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferansId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferansId");

                    b.ToTable("ReferansKategorileri");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Referanslar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferansId")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReferansId");

                    b.ToTable("Referanslar");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.UrunKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("UrunKategorileri");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Urunler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.BlogKategorileri", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.BlogKategorileri", "BlogKategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("BlogKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Bloglar", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.BlogKategorileri", "BlogKategori")
                        .WithMany("Bloglar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.GaleriKategorileri", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.GaleriKategorileri", "GaleriKategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("GaleriKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Image", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.GaleriKategorileri", "GaleriKategori")
                        .WithMany("Image")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GaleriKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.ReferansKategorileri", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.ReferansKategorileri", "ReferansKategori")
                        .WithMany()
                        .HasForeignKey("ReferansId");

                    b.Navigation("ReferansKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Referanslar", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.ReferansKategorileri", "ReferansKategori")
                        .WithMany("Referanslar")
                        .HasForeignKey("ReferansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferansKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.UrunKategorileri", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.UrunKategorileri", "UrunKategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("UrunKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.Urunler", b =>
                {
                    b.HasOne("Admin_Panel_Olusturma.Entities.UrunKategorileri", "UrunKategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UrunKategori");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.BlogKategorileri", b =>
                {
                    b.Navigation("Bloglar");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.GaleriKategorileri", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.ReferansKategorileri", b =>
                {
                    b.Navigation("Referanslar");
                });

            modelBuilder.Entity("Admin_Panel_Olusturma.Entities.UrunKategorileri", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
